### ISSUE TITLE
Support for dynamic custom variable values

### ISSUE THREAD

**Issue by danielbachhuber** [aaroncampbell/wp-google-analytics#5]
It would be great if custom variables supported dynamic values.

For instance, if I added a custom variable named "logged_in", I could use %is_user_logged_in% in the value slot to have it return "true" if the visitor was logged in and "false" if not.

The plugin should come with some number of tokens I can use, but I should be able to filter it to register my own tokens.

**Comment by aaroncampbell** [comment]
Fixed in 1123ddc
